// Sample reels data for testing saved reels functionality
import { browserStorage } from './browser-storage';

// Create a simple test video blob (a 1x1 pixel transparent webm)
const createSampleVideoBlob = () => {
  // This is a minimal webm video file (1 frame, transparent)
  const webmData = new Uint8Array([
    0x1A, 0x45, 0xDF, 0xA3, 0x9F, 0x42, 0x86, 0x81, 0x01, 0x42, 0xF7, 0x81,
    0x01, 0x42, 0xF2, 0x81, 0x04, 0x42, 0xF3, 0x81, 0x08, 0x42, 0x82, 0x84,
    0x77, 0x65, 0x62, 0x6D, 0x42, 0x87, 0x81, 0x02, 0x42, 0x85, 0x81, 0x02
  ]);
  return new Blob([webmData], { type: 'video/webm' });
};

// Sample reels data
const sampleReels = [
  {
    title: "Fashion Trends 2024",
    description: "The latest fashion trends that are taking over social media",
    duration: 30,
    script: "Hey fashion lovers! 🔥 Let's dive into the hottest trends of 2024. First up, we have oversized blazers that are perfect for any season. Next, sustainable fashion is making a huge comeback. Don't forget to subscribe for more style tips!",
    videoUrl: "", // Will be generated by storage system
    authorId: "demo-user",
    sourceArticleId: null,
    metadata: {},
    thumbnailUrl: null,
    videoBlob: createSampleVideoBlob()
  },
  {
    title: "Quick Cooking Tips",
    description: "5-minute meals that will change your life",
    duration: 45,
    script: "Welcome back to my kitchen! Today I'm sharing my top 5-minute meal hacks. First, always prep your ingredients beforehand. Second, invest in quality cookware. These simple tricks will save you hours every week. What's your favorite quick recipe?",
    videoUrl: "", // Will be generated by storage system
    authorId: "demo-user",
    sourceArticleId: null,
    metadata: {},
    thumbnailUrl: null,
    videoBlob: createSampleVideoBlob()
  },
  {
    title: "Morning Motivation",
    description: "Start your day with positive energy",
    duration: 15,
    script: "Good morning everyone! ☀️ Remember, every day is a new opportunity to be amazing. Start with gratitude, set your intentions, and let's make today incredible. You've got this! Drop a ⚡ in the comments if you're ready to conquer your goals!",
    videoUrl: "", // Will be generated by storage system
    authorId: "demo-user",
    sourceArticleId: null,
    metadata: {},
    thumbnailUrl: null,
    videoBlob: createSampleVideoBlob()
  },
  {
    title: "Tech Review: AI Tools",
    description: "Reviewing the latest AI productivity tools",
    duration: 60,
    script: "What's up tech enthusiasts! Today we're diving deep into AI productivity tools that are actually worth your time. I've tested over 20 apps this month, and these are the game-changers. Let's start with the first one that completely transformed my workflow...",
    videoUrl: "", // Will be generated by storage system
    authorId: "demo-user",
    sourceArticleId: null,
    metadata: {},
    thumbnailUrl: null,
    videoBlob: createSampleVideoBlob()
  }
];

export const createSampleReels = async () => {
  try {
    await browserStorage.init();
    
    // Check if we already have sample reels
    const existingReels = await browserStorage.getAllReels();
    if (existingReels.length > 0) {
      console.log('Sample reels already exist');
      return;
    }
    
    // Create sample reels
    console.log('Creating sample reels...');
    for (const reelData of sampleReels) {
      await browserStorage.saveReel(reelData);
    }
    
    console.log('Sample reels created successfully!');
  } catch (error) {
    console.error('Error creating sample reels:', error);
  }
};